name: Build and release a new version of the module

on:
  push:
    branches:
      - 'main'

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - name: Set DATE variable
        run: echo "DATE=$(date +'%y%m%d')" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set version
        run:  |
          sed -i "s/version=v250101/version=v${DATE}/" module.prop
          sed -i "s/versionCode=250101/versionCode=${DATE}/" module.prop
          sed -i "s/\"version\": \"v250101\",/\"version\": \"v${DATE}\",/" update.json
          sed -i "s/\"versionCode\": \"250101\",/\"versionCode\": \"${DATE}\",/" update.json
          sed -i "s/\"zipUrl\": \"https:\/\/github.com\/EmilienCourt\/kernelsu-module-openeuicc\/releases\/download\/v250101\/module.zip\",/\"zipUrl\": \"https:\/\/github.com\/EmilienCourt\/kernelsu-module-openeuicc\/releases\/download\/v${DATE}\/module.zip\",/" update.json
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Build kernelsu-module-openeuicc
        run: bash build.sh

      - name: Release module.zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: module.zip
          asset_name: module.zip
          tag: v${{ env.DATE }}
          overwrite: true
          body: ${{ github.event.head_commit.message }}

      - name: Release update.json
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: update.json
          asset_name: update.json
          tag: v${{ env.DATE }}
          overwrite: true
          body: ${{ github.event.head_commit.message }}