name: Build a new release of the module

on:
  push:
    branches:
      - 'main'

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - name: Set DATE variable
        run: echo "DATE=$(date +'%y%m%d')" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Build kernelsu-module-openeuicc
        run: bash build.sh

      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: module.zip
          asset_name: module.zip
          tag: v${{ env.DATE }}
          overwrite: true
          body: ${{ github.event.head_commit.message }}